### ISSUE TITLE
CVButton shadow onhover

### ISSUE THREAD

**Issue by brendanmanning** [Hack4ImpactTemple/CrowdVet_#15]
Add nohover property so that CVButton has no effect onhover when being used as a generic colored div

**Comment by lawja** [comment]
Can you show a replicable example of this? This shouldn't be too bad to fix.

**Comment by lawja** [comment]
any update on this?

**Comment by brendanmanning** [comment]
I'll try to work on this over the weekend - sorry i've been busy with the internship
