### ISSUE TITLE
[PracticePage] IDs should not be hardcoded into onPageLoad

### ISSUE THREAD

**Issue by brendanmanning** [Hack4ImpactTemple/CrowdVet_#18]
See somewhere around line 215
![Captura de pantalla 2019-05-11 a la(s) 1 07 52 p  m](https://user-images.githubusercontent.com/14865682/57572810-d5079c80-73ed-11e9-9cf9-170eaf84d54c.png)

**Comment by lawja** [comment]
so the reason why I hardcoded this was because I'm unaware as to how I would go about getting all loan IDs from the API. Any suggestions?

Also, this page is entirely contingent upon having data that has ID labeled rows, which may be an issue...

**Comment by brendanmanning** [comment]
I think a good compromise would be to just move those hardcoded values into one of the configs.
That way if they ever want to add another org, they know where to go.

**Comment by brendanmanning** [comment]
Actually, this should probably stay open until we've done the config thing.

**Comment by lawja** [comment]
Done. Users can now set the loan IDs, theory videos, and add additional FAQ questions if they wish
