### ISSUE TITLE
Update footer links

### ISSUE THREAD

**Issue by brendanmanning** [Hack4ImpactTemple/CrowdVet_#21]
Also, we need to fix some of the CSS, which doesn't really place everything right

**Comment by lawja** [comment]
adding the links now.

What isn't placed right? I'm not sure what you mean by this

**Comment by lawja** [comment]
Ours:
<img width="832" alt="Screen Shot 2019-05-30 at 1 45 58 PM" src="https://user-images.githubusercontent.com/9260091/58652335-506bb800-82e1-11e9-9947-b96686cb590c.png">
Current Kiva:
<img width="1019" alt="Screen Shot 2019-05-30 at 1 46 08 PM" src="https://user-images.githubusercontent.com/9260091/58652336-506bb800-82e1-11e9-9e30-e278a4781fcd.png">

Are you referring to the "Work with us" section?

I don't think we need to / should worry about the color scheme

**Comment by brendanmanning** [comment]
I might have been viewing it with weird dimensions or something. My bad.
