### ISSUE TITLE
@Jake's page CSS broken

### ISSUE THREAD

**Issue by brendanmanning** [Hack4ImpactTemple/CrowdVet_#22]
![Captura de pantalla 2019-05-13 a la(s) 1 38 43 a  m](https://user-images.githubusercontent.com/14865682/57598099-de912180-751f-11e9-9290-830448f42f01.png)

**Comment by lawja** [comment]
resolved
<img width="1279" alt="Screen Shot 2019-05-30 at 1 29 08 PM" src="https://user-images.githubusercontent.com/9260091/58651298-ef42e500-82de-11e9-8643-86e1063b800f.png">

(the text is scrollable)

**Comment by lawja** [comment]
I'm going to close this unless you have any outstanding reasons not to
