### ISSUE TITLE
Get ProfileLead working

### ISSUE THREAD

**Issue by brendanmanning** [Hack4ImpactTemple/CrowdVet_#23]
* What information can we exclude
* What do we show when nobody's logged in?

**Comment by lawja** [comment]
> What information should we exclude?

What information do we have?

> What do we show when nobody's logged in?

I'll add a "not logged in" splash div. It's not the most elegant solution, but it works and gets the point across

**Comment by lawja** [comment]
Ours:
<img width="832" alt="Screen Shot 2019-05-30 at 1 45 58 PM" src="https://user-images.githubusercontent.com/9260091/58652335-506bb800-82e1-11e9-9947-b96686cb590c.png">
Current Kiva:
<img width="1019" alt="Screen Shot 2019-05-30 at 1 46 08 PM" src="https://user-images.githubusercontent.com/9260091/58652336-506bb800-82e1-11e9-9e30-e278a4781fcd.png">

Are you referring to the "Work with us" section?

I don't think we need to / should worry about the footer

**Comment by lawja** [comment]
oops wrong thread

**Comment by lawja** [comment]
Not logged in:
<img width="1280" alt="Screen Shot 2019-05-30 at 2 42 16 PM" src="https://user-images.githubusercontent.com/9260091/58657886-3e901200-82ed-11e9-81ec-91d60e9cb7d7.png">
Logged in:
<img width="1280" alt="Screen Shot 2019-05-30 at 3 11 11 PM" src="https://user-images.githubusercontent.com/9260091/58657887-3e901200-82ed-11e9-8a15-8d16e1b3e0fc.png">

Here's what I had in mind. We can make the logged in more complicated but that's entirely dependent on how much info we have for users in the database.

**Comment by lawja** [comment]
Also, in Auth.js I fixed changed all instances of InnerHtml to InnerText, in order to prevent XSS. An example is shown below.
<img width="665" alt="Screen Shot 2019-05-30 at 3 13 57 PM" src="https://user-images.githubusercontent.com/9260091/58658066-a8a8b700-82ed-11e9-8d5f-a6c3214056ea.png">

**Comment by brendanmanning** [comment]
Yeah that's a good catch with the innerHTML. The blur view would be really nice btw

**Comment by lawja** [comment]
this is now done.
