### ISSUE TITLE
Profile Page?

### ISSUE THREAD

**Issue by lawja** [Hack4ImpactTemple/CrowdVet_#28]
So in the sub-navbar (shown below), there is a "Profile" link, that currently leads to nowhere.
<img width="1280" alt="Screen Shot 2019-05-31 at 4 04 39 PM" src="https://user-images.githubusercontent.com/9260091/58733354-538aa500-83c2-11e9-9a29-c849cdb8536f.png">

Do we want to add a profile page similar to the one shown on [the current CrowdVet site](https://www.crowdvet.org/vet/enterprises)?

**Comment by brendanmanning** [comment]
The only information which would be included in the page that's not in the ProfileHeader would be the vetting history, correct? That is pretty important, so we probably should find some way to do that if we have time.

**Comment by lawja** [comment]
Yeah, I agree. Let's get the config vars working, the documentation up to date, and then we can try and tackle this.

**Comment by lawja** [comment]
this is a wip, really just waiting on understanding the votes data so I can slap together some filler chart or something

**Comment by brendanmanning** [comment]
If you finished this, can you close the issue?

**Comment by lawja** [comment]
yeah, sorry I forgot to
