### ISSUE TITLE
On logout, the redirect page has a minor CSS issue

### ISSUE THREAD

**Issue by lawja** [Hack4ImpactTemple/CrowdVet_#29]
When on the redirect page, the correct background color isn't displayed below the footer (shown below).
<img width="1280" alt="Screen Shot 2019-05-31 at 4 40 58 PM" src="https://user-images.githubusercontent.com/9260091/58733651-183ca600-83c3-11e9-876e-3db3f4d0264b.png">
The white are (on the very bottom) should be `var(--dark-green)`

**Comment by lawja** [comment]
Actually, how about we make the entire page just "If you are not redirected automatically in a few seconds, click here". I think this will make things look overall less broken. What do you think @brendanmanning ?

**Comment by brendanmanning** [comment]
Like a blank white page with just that text written?

**Comment by lawja** [comment]
Exactly. I just think that's less confusing than the current page. Or we could have a spinner and the text "Logging out". Either one works imo

**Comment by lawja** [comment]
this is fixed; I'm pushing the fix to master soon
