### ISSUE TITLE
Instructions for adding a new organization / adding hardcoded things to the config

### ISSUE THREAD

**Issue by brendanmanning** [Hack4ImpactTemple/CrowdVet_#30]
As we mentioned in #18, there should be some well-documented way for Kiva to add new sample organization. As I can think of now, there are a few things they'd need to do:
* Hardcode the ID into the config file
* Copy the applications materials into the correct folder
* Update the excel spreadsheets (crowd & kiva voting data)
* This is probably not exhaustive

We're going to have to add a section to README that describes this process

**Comment by lawja** [comment]
Yeah I agree, good idea.

**Comment by lawja** [comment]
let's make this have a broader scope; such as putting the FAQs in the config as well. We should pick out all constants / hardcoded variables in our code and shift them to a config file. I'm going to update this issue to reflect this

**Comment by lawja** [comment]
added this in the README (config section, number 2)
